const langObj = {
    'en': {
        'hero-heading': 'The simplest way to work in telehealth',
        'hero-text': 'At Letmed, our mission is to change the way healthcare works by focusing on the effectiveness of treatment outcomes.',
        'features-heading': 'Why Letmed',
        'features-text': 'Find out how you can gain more balance and freedom in your medical career with the power of Letmed telemedicine oportunities.',
        'item-heading1': 'Easy start',
        'item-text1': 'Letmed provide you with everything you need to deliver high-quality virtual patient care. The first step is to fill out the pre-application form so we can learn more about you to find the best potential virtual care job opportunities',
        'item-heading2': 'Freedom',
        'item-text2': "Our telehealth solution is fully asynchronous , so you decide which patients and when you want to take care of and it's up to you how much time you devote to each patient. Without making an appointment, you work at any free time",
        'item-heading3': 'Automation',
        'item-text3': 'An intelligent medical questionnaire created by doctors collects preliminary patient data and analyzes it to help you in diagnosis and treatment. A personal template creation system helps you spend more time communicating with the patient than filling out EHRs.',
        'schedule-heading': 'Your schedule is about to be yours again',
        'schedule-text': 'Letmed White Label solution tailored to your needs will allow you to provide your patients with even more convenient and professional care.',
        'schedule-li1': 'Fast launch and integration',
        'schedule-li2': 'Flexible schedule',
        'schedule-li3': 'Custom treatment options',
        'schedule-li4': 'Personalized medical templates and tools',
        'form-heading': 'Join to team',
        'form-text': 'You can ask us a question. Leave your contact information and we will get back to you. We will answer you as soon as possible',
        'form-name': 'Name',
        'form-tel': 'Your phone number',
        'form-mail': 'Your e-mail',
        'form-consent': 'I consent to the processing of my',
        'form-link': 'personal data',
        'form-btn': 'Contact',
        'form-placeholder': 'Start typing something',
        'nav-services': 'Services',
        'nav-contact': 'Contact',
        'nav-cooperation': 'Cooperation'
    },
    'pl': {
        'hero-heading': 'Najprostszy sposób pracy w telemedycynie',
        'hero-text': 'W Letmed naszą misją jest zmiana sposobu działania opieki zdrowotnej poprzez skupienie się na skuteczności wyników leczenia.',
        'features-heading': 'Dlaczego Letmed',
        'features-text': 'Dajemy Lekarzom możliwość świadczenia najwyższej jakości wirtualnej opieki medycznej na własnych warunkach. Dowiedz się, jak możesz zyskać większą równowagę i swobodę w swojej karierze medycznej dzięki możliwościom telemedycyny z firmą Letmed.',
        'item-heading1': 'Łatwy start',
        'item-text1': 'Letmed zapewni Ci wszystko, czego potrzebujesz, aby prowadzić wysokiej jakości wirtualną opiekę nad pacjentem. Pierwszym krokiem jest wypełnienie formularza przedaplikacyjnego, abyśmy mogli dowiedzieć się więcej o Tobie i znaleźć najlepsze potencjalne oferty pracy i zlecenia medyczne w wirtualnej opiece zdrowotnej.',
        'item-heading2': 'Swoboda',
        'item-text2': "Nasze rozwiązanie telemedyczne jest w pełni asynchroniczne, więc to Ty decydujesz, którymi pacjentami i kiedy chcesz się zaopiekować , jak również ile czasu poświęcisz każdemu pacjentowi. Bez kalendarza, pracujesz w dowolnym wolnym czasie.",
        'item-heading3': 'Automatyzacja',
        'item-text3': 'Inteligentne ankiety medyczne tworzone przez lekarzy zbierają wstępne dane o pacjencie i analizują je, aby pomóc Ci w diagnostyce i leczeniu. System tworzenia osobistych szablonów pomaga spędzać więcej czasu na komunikowaniu się z pacjentem niż wypełnianie EHR lub napisaniu rutynowych rekomendacji leczenia.',
        'schedule-heading': 'Twój harmonogram znów będzie Twój',
        'schedule-text': 'Dostosowane do Twoich potrzeb rozwiązanie Letmed White Label pozwoli Ci zapewnić swoim pacjentom jeszcze wygodniejszą i profesjonalną opiekę.',
        'schedule-li1': 'Szybkie uruchamianie i integracja',
        'schedule-li2': 'Elastyczny harmonogram',
        'schedule-li3': 'Konfigurowalne opcje leczenia',
        'schedule-li4': 'Spersonalizowane szablony i narzędzia medyczne',
        'form-heading': 'Dołącz do zespołu',
        'form-text': 'Jeśli chcesz dołączyć do naszego zespołu, zostaw swoje dane kontaktowe, a odezwiemy się do Ciebie.',
        'form-name': 'Imię',
        'form-tel': 'Twój numer telefonu',
        'form-mail': 'Twój e-mail',
        'form-consent': 'Wyrażam zgodę na przetwarzanie moich',
        'form-link': 'danych osobowych',
        'form-btn': 'Wyślij',
        'form-placeholder': 'Zacznij coś pisać',
        'nav-services': 'Usługi',
        'nav-contact': 'Kontakt',
        'nav-cooperation': 'Współpraca',
    }
}

export { langObj }