const langObj = {
    'en': {
        'hero-heading': 'Health plans On-demand',
        'hero-text': 'Take control of your health with personalized, On-demand medical plans powered by Letmed licensed healthcare professionals and AI engine',
        'hero-btn': 'Get care',
        'feature-text1': 'Certified clinicians',
        'feature-text2': 'Health care within minutes',
        'feature-text3': 'Follow-up care',
        'section-plans-heading': 'Get access to various treatment plans',
        'plan-title1': 'Prescription refill',
        'plan-text1': 'Hypertension',
        'plan-title2': 'Treatment plan',
        'plan-text2': 'Cough',
        'plan-title3': 'New prescription',
        'plan-text3': 'Contraception',
        'plan-title4': 'Ongoing care',
        'plan-text4': 'Women’s health',
        'plan-title5': 'Metformin',
        'plan-text5': 'Medicates',
        'plan-title6': 'Health goal',
        'plan-text6': 'Diabetes control',
        'plan-title7': 'Treatment plan',
        'plan-text7': 'COVID',
        'plan-title8': 'Diagnostic tests',
        'plan-text8': 'Allergy',

        'section-tools-heading': 'All-in-one digital health tool',
        'discussion-heading': 'New treatment',
        'discussion-text1': 'I would also like to add that I am constantly thirsty and feeling tired',
        'discussion-p': 'Based on the information you have provided, you will likely benefit from a following prescription-based treatment plan',
        'discussion-p2': ' Therapy plan: Diabetic',
        'health-heading': 'General practice care',
        'health-title1': 'Health tasks',
        'health-text1': 'Check your blood sugar levels. Reduce the amount of fatty foods in your diet.',
        'health-title2': 'Medications',
        'med1': 'Metformin',
        'health-descr': 'Take 1 tablet by mouth daily for days 1-10, then take 1 tablet by mouth twice daily for the rest of treatment , after a meal.',
        'health-title3': 'Tests',
        'health-p': 'Blood test',
        'health-span': 'Some issues',
        'follow-heading': 'Diabetes therapy',
        'follow-subtitle': 'LetMed care',
        'follow-title1': 'How is your current treatment working for you?',
        'follow-answer1': 'Great',
        'follow-answer2': 'Fine',
        'follow-answer3': "Doesn't help",
        'follow-title2': 'Have you experienced any side effects?',
        'follow-answer-wide1': "I haven’t had side effects",
        'follow-answer-wide2': 'I have had side effects.',
        'tools-btn1': 'Discussion',
        'tools-btn2': 'Health plan',
        'tools-btn3': 'Follow-up',
        'tools-text-discussion1': 'High quality health care available 24/7 , no appointment, waiting rooms or insurance needed',
        'tools-text-discussion2': 'Answer a few questions about your health, lifestyle, and family history. So that the doctor can understand your needs and create an appropriate treatment plan for you.',
        'tools-text-health': 'The medical specialist will assess your symptoms, discuss your treatment plan with you, prescribe medication if needed, and can refer you to a specialist or lab.',
        'tools-text-span1': 'E-prescriptions',
        'tools-text-span2': 'Recommendations',
        'tools-text-span3': 'E-refferrals',
        'tools-text-follow': 'Set personal health goals and monitor your progress. Your healthcare medical secialist on the Letmed platform is here to help if treatment is going wrong. Message them any time to discuss your issues',
        'tools-cta': 'Get therapy',
        'section-goals-heading': 'Reach your health goals with Letmed',
        'goals-wrapper-text': 'At Letmed We know how your care plans are going so you can achieve your medical goals with confidence.',
        'goals-span-title1': 'Diabetes',
        'goals-span-title2': 'Covid',
        'goals-span-title3': 'Flu',
        'goals-span-title4': 'Contraception',
        'goals-span-span': 'Health goal achieved',
        'goals-text1': 'Blood glucoze level is normal. Metformin treatment without side effects.',
        'goals-text2': 'Treatment was fine.',
        'goals-text3': 'Treatment plan was excelent.',
        'goals-text4': 'Treatment was excelent.',
        'form-heading': 'Any more questions?',
        'form-text': 'You can ask us a question. Leave your contact information and we will get back to you. We will answer you as soon as possible',
        'form-name': 'Name',
        'form-tel': 'Your phone number',
        'form-mail': 'Your e-mail',
        'form-consent': 'I consent to the processing of my',
        'form-link': 'personal data',
        'form-btn': 'Contact',
        'form-placeholder': 'Start typing something',
        'section-treat-heading': "What We Don’t Treat",
        'treat-descr': "While our providers are able to treat most common issues, there are conditions that we don’t treat. Please see an in-person doctor or hospital if you experience any of the following:",
        'treat-li1': 'Traumatic injury to the brain or spinal cord',
        'treat-li2': 'Chest pain and/or numbness',
        'treat-li3': 'Severe burns',
        'treat-li4': 'Ear infections',
        'treat-li5': 'Vomiting or coughing up blood',
        'treat-li6': 'Broken bones',
        'treat-li7': 'Loss of consciousness',
        'treat-li8': 'Lacerations',
        'treat-text': 'Our doctors cannot write prescriptions for controlled substances such as codeine or oxycodone. Please see your doctor in person if you need a drug that is a controlled substance.',
        'treat-warning': 'If you think that your health condition is life-threatening or requires urgent medical attention',
        'treat-span': 'Please call 112',
        'section-questions-heading': 'Frequently asked questions',
        'question-title1': 'How long does it take to hear back from your doctor?',
        'question-answer1': 'The entire healthcare team on the Letmed platform are licensed healthcare professionals. Every doctor goes through a licensing and background check and verification process. When you message or chat with a doctor on the Letmed platform, you can see their resume and medical license.',
        'question-title2': 'Who is Letmed for?',
        'question-answer2': 'The entire healthcare team on the Letmed platform are licensed healthcare professionals. Every doctor goes through a licensing and background check and verification process. When you message or chat with a doctor on the Letmed platform, you can see their resume and medical license.',
        'question-title3': 'Who are the health care professionals at Letmed?',
        'question-answer3': 'The entire healthcare team on the Letmed platform are licensed healthcare professionals. Every doctor goes through a licensing and background check and verification process. When you message or chat with a doctor on the Letmed platform, you can see their resume and medical license.',
        'question-title4': 'Can I use any pharmacy?',
        'question-answer4': 'The entire healthcare team on the Letmed platform are licensed healthcare professionals. Every doctor goes through a licensing and background check and verification process. When you message or chat with a doctor on the Letmed platform, you can see their resume and medical license.',
        'question-title5': 'Is my personal information secure?',
        'question-answer5': 'The entire healthcare team on the Letmed platform are licensed healthcare professionals. Every doctor goes through a licensing and background check and verification process. When you message or chat with a doctor on the Letmed platform, you can see their resume and medical license.',
        'nav-lang': 'Services',
        'nav-contact': 'Contact',
        'nav-cooperation': 'Cooperation'
    },
    'pl': {
        'hero-heading': 'Opieka zdrowotna pracująca dla Ciebie',
        'hero-text': 'Przejmij kontrolę nad swoim zdrowiem, zarządzając spersonalizowanymi planami leczenia na żądanie z licencjonowanymi pracownikami służby zdrowia.',
        'hero-btn': 'Rozpocznij',
        'feature-text1': 'Certyfikowani pracownicy służby zdrowia',
        'feature-text2': 'Opieka zdrowotna w kilka minut',
        'feature-text3': 'Plany leczenia na żądanie',
        'section-plans-heading': 'Uzyskaj dostęp do różnych planów leczenia',
        'plan-title1': 'Przedłużenie recepty',
        'plan-text1': 'Nadciśnienie',
        'plan-title2': 'Plan leczenia',
        'plan-text2': 'Kaszel',
        'plan-title3': 'Nowe leczenie',
        'plan-text3': 'Antykoncepcja',
        'plan-title4': 'Stała opieka',
        'plan-text4': 'Zdrowie kobiet',
        'plan-title5': 'Metformina',
        'plan-text5': 'Leki',
        'plan-title6': 'Cel zdrowotny',
        'plan-text6': 'Kontrola cukrzycy',
        'plan-title7': 'Plan leczenia',
        'plan-text7': 'COVID',
        'plan-title8': 'Testy diagnostyczne',
        'plan-text8': 'Alergia',
        'section-tools-heading': 'Kompleksowe cyfrowe narzędzie zdrowotne',
        'discussion-heading': 'Nowe leczenie',
        'discussion-text1': 'Dodam też, że ciągle jestem spragniona i czuję się zmęczona',
        'discussion-p': 'Na podstawie podanych przez Ciebie informacji prawdopodobnie skorzystasz z następującego planu leczenia na receptę',
        'discussion-p2': 'Plan opieki: Cukrzyca',
        'health-heading': 'Opieka lekarza Internisty',
        'health-title1': 'Zadania zdrowotne',
        'health-text1': 'Sprawdzaj poziom cukru we krwi. Zmniejsz ilość tłustych potraw w swojej diecie.',
        'health-title2': 'Leki',
        'med1': 'Metformina',
        'health-descr': 'Przyjmować 1 tabletkę doustnie dziennie przez 1-10 dni, następnie 1 tabletkę doustnie dwa razy dziennie przez resztę leczenia, po posiłku.',
        'health-title3': 'Badania',
        'health-p': 'Badania krwi',
        'health-span': 'Poza normą',
        'follow-heading': 'Terapia cukrzycy',
        'follow-subtitle': 'LetMed opieka',
        'follow-title1': 'Jak działa Twoja obecna terapia?',
        'follow-answer1': 'Super',
        'follow-answer2': 'Dobrze',
        'follow-answer3': 'Nie pomaga',
        'follow-title2': 'Czy doświadczyłeś jakichś skutków ubocznych?',
        'follow-answer-wide1': 'Nie miałem skutków ubocznych',
        'follow-answer-wide2': 'Miałem skutki uboczne.',
        'tools-btn1': 'Konsultacja',
        'tools-btn2': 'Plan opieki',
        'tools-btn3': 'Kontynuacja opieki',
        'tools-text-discussion1': 'Wysokiej jakości opieka zdrowotna dostępna 24/7 , bez konieczności umawiania się na wizytę, poczekalni ani ubezpieczenia',
        'tools-text-discussion2': 'Odpowiedz na kilka pytań dotyczących Twojego zdrowia, stylu życia i historii medycznej, aby lekarz mógł zrozumieć Twoje potrzeby i stworzyć dla Ciebie odpowiedni plan leczenia.',
        'tools-text-health': 'Specjalista medyczny oceni Twoje objawy, omówi z Tobą plan leczenia, w razie potrzeby przepisze leki i może skierować Cię do specjalisty lub laboratorium.',
        'tools-text-span1': 'E-recepta',
        'tools-text-span2': 'Zalecenia',
        'tools-text-span3': 'E-skierowania',
        'tools-text-follow': 'Ustal osobiste cele zdrowotne i monitoruj swoje postępy. Twój specjalista ds. opieki zdrowotnej na platformie Letmed jest tutaj, aby pomóc, jeśli leczenie się nie powiedzie. Wyślij do nich wiadomość w dowolnym momencie, aby omówić swoje problemy',
        'tools-cta': 'Rozpocznij',
        'section-goals-heading': 'Osiągaj swoje cele zdrowotne z Letmed',
        'goals-wrapper-text': 'W Letmed wiemy, jak postępują Twoje plany opieki, dzięki czemu możesz śmiało osiągnąć swoje cele medyczne.',
        'goals-span-title1': 'Cukrzyca',
        'goals-span-title2': 'Covid',
        'goals-span-title3': 'Grypa',
        'goals-span-title4': 'Antykoncepcja',
        'goals-span-span': 'Terapia zakończona',
        'goals-text1': 'Poziom glukozy we krwi jest normalny. Kuracja metforminą bez skutków ubocznych.',
        'goals-text2': 'Leczenie było w porządku.',
        'goals-text3': 'Plan leczenia był doskonały.',
        'goals-text4': 'Leczenie było doskonałe.',
        'form-heading': 'Napisz do Nas',
        'form-text': 'Możesz zadać nam pytanie. Zostaw swoje dane kontaktowe, a my skontaktujemy się z Tobą. Odpowiemy Ci tak szybko, jak to możliwe',
        'form-name': 'Imię',
        'form-tel': 'Twój numer telefonu',
        'form-mail': 'Twój e-mail',
        'form-consent': 'Wyrażam zgodę na przetwarzanie moich',
        'form-link': 'danych osobowych',
        'form-btn': 'Wyślij',
        'form-placeholder': 'Zacznij coś pisać',
        'section-treat-heading': "Czego nie leczymy",
        'treat-descr': "Chociaż nasi dostawcy są w stanie leczyć najczęstsze problemy, istnieją schorzenia, których nie leczymy. Skontaktuj się z lekarzem lub szpitalem, jeśli wystąpi którykolwiek z poniższych objawów:",
        'treat-li1': 'Urazowe uszkodzenie mózgu lub rdzenia kręgowego',
        'treat-li2': 'Ból w klatce piersiowej i/lub drętwienie',
        'treat-li3': 'Poważne oparzenia',
        'treat-li4': 'Infekcja ucha',
        'treat-li5': 'Wymioty lub kaszel krwią',
        'treat-li6': 'Połamane kości',
        'treat-li7': 'Utrata przytomności',
        'treat-li8': 'Rany',
        'treat-text': 'Nasi lekarze nie mogą wypisywać recept na substancje kontrolowane, takie jak kodeina czy oksykodon. Jeśli potrzebujesz leku, który jest substancją kontrolowaną, skontaktuj się z lekarzem osobiście.',
        'treat-warning': 'Jeśli uważasz, że Twój stan zdrowia zagraża życiu lub wymaga pilnej pomocy medycznej',
        'treat-span': 'Zadzwoń pod numer 112',
        'section-questions-heading': 'Często Zadawane Pytania',
        'question-title1': 'Jak długo trzeba czekać na odpowiedź od lekarza?',
        'question-answer1': 'Cały zespół opieki zdrowotnej na platformie Letmed to licencjonowani pracownicy służby zdrowia. Każdy lekarz przechodzi proces licencjonowania i sprawdzania przeszłości oraz weryfikacji. Gdy wysyłasz wiadomość lub czatujesz z lekarzem na platformie Letmed, możesz zobaczyć jego CV i licencję medyczną.',
        'question-title2': 'Dla kogo jest Letmed?',
        'question-answer2': 'Cały zespół opieki zdrowotnej na platformie Letmed to licencjonowani pracownicy służby zdrowia. Każdy lekarz przechodzi proces licencjonowania i sprawdzania przeszłości oraz weryfikacji. Gdy wysyłasz wiadomość lub czatujesz z lekarzem na platformie Letmed, możesz zobaczyć jego CV i licencję medyczną.',
        'question-title3': 'Kim są pracownicy służby zdrowia w Letmed?',
        'question-answer3': 'Cały zespół opieki zdrowotnej na platformie Letmed to licencjonowani pracownicy służby zdrowia. Każdy lekarz przechodzi proces licencjonowania i sprawdzania przeszłości oraz weryfikacji. Gdy wysyłasz wiadomość lub czatujesz z lekarzem na platformie Letmed, możesz zobaczyć jego CV i licencję medyczną.',
        'question-title4': 'Czy mogę korzystać z dowolnej apteki?',
        'question-answer4': 'Cały zespół opieki zdrowotnej na platformie Letmed to licencjonowani pracownicy służby zdrowia. Każdy lekarz przechodzi proces licencjonowania i sprawdzania przeszłości oraz weryfikacji. Gdy wysyłasz wiadomość lub czatujesz z lekarzem na platformie Letmed, możesz zobaczyć jego CV i licencję medyczną.',
        'question-title5': 'Czy moje dane osobowe są bezpieczne?',
        'question-answer5': 'Cały zespół opieki zdrowotnej na platformie Letmed to licencjonowani pracownicy służby zdrowia. Każdy lekarz przechodzi proces licencjonowania i sprawdzania przeszłości oraz weryfikacji. Gdy wysyłasz wiadomość lub czatujesz z lekarzem na platformie Letmed, możesz zobaczyć jego CV i licencję medyczną.',
        'nav-lang': 'Usługi',
        'nav-contact': 'Kontakt',
        'nav-cooperation': 'Współpraca'
    }
}





export { langObj }

