const langObj = {
    'pl': {
        'hero-heading': 'Opieka zdrowotna pracująca dla Ciebie',
        'hero-text': 'Przejmij kontrolę nad swoim zdrowiem, zarządzając spersonalizowanymi planami leczenia na żądanie z licencjonowanymi pracownikami służby zdrowia.',
        'hero-btn': 'Rozpocznij',
        'feature-text1': 'Certyfikowani pracownicy służby zdrowia',
        'feature-text2': 'Opieka zdrowotna w kilka minut',
        'feature-text3': 'Plany leczenia na żądanie',
        'section-plans-heading': 'Uzyskaj dostęp do różnych planów leczenia',
        'plan-title1': 'Przedłużenie recepty',
        'plan-text1': 'Nadciśnienie',
        'plan-title2': 'Plan leczenia',
        'plan-text2': 'Kaszel',
        'plan-title3': 'Nowe leczenie',
        'plan-text3': 'Antykoncepcja',
        'plan-title4': 'Stała opieka',
        'plan-text4': 'Zdrowie kobiet',
        'plan-title5': 'Metformina',
        'plan-text5': 'Leki',
        'plan-title6': 'Cel zdrowotny',
        'plan-text6': 'Kontrola cukrzycy',
        'plan-title7': 'Plan leczenia',
        'plan-text7': 'COVID',
        'plan-title8': 'Testy diagnostyczne',
        'plan-text8': 'Alergia',
        'section-tools-heading': 'Kompleksowe cyfrowe narzędzie zdrowotne',
        'discussion-heading': 'Nowe leczenie',
        'discussion-text1': 'Dodam też, że ciągle jestem spragniona i czuję się zmęczona',
        'discussion-p': 'Na podstawie podanych przez Ciebie informacji prawdopodobnie skorzystasz z następującego planu leczenia na receptę',
        'discussion-p2': 'Plan opieki: Cukrzyca',
        'health-title1': 'Zadania zdrowotne',
        'health-text1': 'Sprawdzaj poziom cukru we krwi. Zmniejsz ilość tłustych potraw w swojej diecie.',
        'health-title2': 'Leki',
        'med1': 'Metformina',
        'health-descr': 'Przyjmować 1 tabletkę doustnie dziennie przez 1-10 dni, następnie 1 tabletkę doustnie dwa razy dziennie przez resztę leczenia, po posiłku.',
        'health-title3': 'Badania',
        'health-p': 'Badania krwi',
        'follow-subtitle': 'LetMed opieka',
        'follow-title1': 'Jak działa Twoja obecna terapia?',
        'follow-answer1': 'Super',
        'follow-answer2': 'Dobrze',
        'follow-answer3': 'Nie pomaga',
        'follow-title2': 'Czy doświadczyłeś jakichś skutków ubocznych?',
        'follow-answer-wide1': 'Nie miałem skutków ubocznych',
        'follow-answer-wide2': 'Miałem skutki uboczne.',
        'tools-btn1': 'Konsultacja',
        'tools-btn2': 'Plan opieki',
        'tools-btn3': 'Kontynuacja opieki',
        'tools-text-discussion1': 'Wysokiej jakości opieka zdrowotna dostępna 24/7 , bez konieczności umawiania się na wizytę, poczekalni ani ubezpieczenia',
        'tools-text-discussion2': 'Odpowiedz na kilka pytań dotyczących Twojego zdrowia, stylu życia i historii medycznej, aby lekarz mógł zrozumieć Twoje potrzeby i stworzyć dla Ciebie odpowiedni plan leczenia.',
        'tools-text-health': 'Specjalista medyczny oceni Twoje objawy, omówi z Tobą plan leczenia, w razie potrzeby przepisze leki i może skierować Cię do specjalisty lub laboratorium.',
        'tools-text-span1': 'E-recepta',
        'tools-text-span2': 'Zalecenia',
        'tools-text-span3': 'E-skierowania',
        'tools-text-follow': 'Ustal osobiste cele zdrowotne i monitoruj swoje postępy. Twój specjalista ds. opieki zdrowotnej na platformie Letmed jest tutaj, aby pomóc, jeśli leczenie się nie powiedzie. Wyślij do nich wiadomość w dowolnym momencie, aby omówić swoje problemy',
        'tools-cta': 'Rozpocznij',
        'section-goals-heading': 'Osiągaj swoje cele zdrowotne z Letmed',
        'goals-wrapper-text': 'W Letmed wiemy, jak postępują Twoje plany opieki, dzięki czemu możesz śmiało osiągnąć swoje cele medyczne.',
        'goals-span-title1': 'Cukrzyca',
        'goals-span-title2': 'Covid',
        'goals-span-title3': 'Grypa',
        'goals-span-title4': 'Antykoncepcja',
        'goals-span-span': 'Terapia zakończona',
        'goals-text1': 'Poziom glukozy we krwi jest normalny. Kuracja metforminą bez skutków ubocznych.',
        'goals-text2': 'Leczenie było w porządku.',
        'goals-text3': 'Plan leczenia był doskonały.',
        'goals-text4': 'Leczenie było doskonałe.',
        'form-heading': 'Napisz do Nas',
        'form-text': 'Możesz zadać nam pytanie. Zostaw swoje dane kontaktowe, a my skontaktujemy się z Tobą. Odpowiemy Ci tak szybko, jak to możliwe',
        'form-name': 'Imię',
        'form-tel': 'Twój numer telefonu',
        'form-mail': 'Twój e-mail',
        'form-consent': 'Wyrażam zgodę na przetwarzanie moich',
        'form-link': 'danych osobowych',
        'form-btn': 'Wyślij',
        'form-placeholder': 'Zacznij coś pisać',
        'section-treat-heading': "Czego nie leczymy",
        'treat-descr': "Chociaż nasi dostawcy są w stanie leczyć najczęstsze problemy, istnieją schorzenia, których nie leczymy. Skontaktuj się z lekarzem lub szpitalem, jeśli wystąpi którykolwiek z poniższych objawów:",
        'treat-li1': 'Urazowe uszkodzenie mózgu lub rdzenia kręgowego',
        'treat-li2': 'Ból w klatce piersiowej i/lub drętwienie',
        'treat-li3': 'Poważne oparzenia',
        'treat-li4': 'Infekcja ucha',
        'treat-li5': 'Wymioty lub kaszel krwią',
        'treat-li6': 'Połamane kości',
        'treat-li7': 'Utrata przytomności',
        'treat-li8': 'Rany',
        'treat-text': 'Nasi lekarze nie mogą wypisywać recept na substancje kontrolowane, takie jak kodeina czy oksykodon. Jeśli potrzebujesz leku, który jest substancją kontrolowaną, skontaktuj się z lekarzem osobiście.',
        'treat-warning': 'Jeśli uważasz, że Twój stan zdrowia zagraża życiu lub wymaga pilnej pomocy medycznej',
        'treat-span': 'Zadzwoń pod numer 112',
        'section-questions-heading': 'Często Zadawane Pytania',
        'question-title1': 'Jak długo trzeba czekać na odpowiedź od lekarza?',
        'question-answer1': 'Cały zespół opieki zdrowotnej na platformie Letmed to licencjonowani pracownicy służby zdrowia. Każdy lekarz przechodzi proces licencjonowania i sprawdzania przeszłości oraz weryfikacji. Gdy wysyłasz wiadomość lub czatujesz z lekarzem na platformie Letmed, możesz zobaczyć jego CV i licencję medyczną.',
        'question-title2': 'Dla kogo jest Letmed?',
        'question-answer2': 'Cały zespół opieki zdrowotnej na platformie Letmed to licencjonowani pracownicy służby zdrowia. Każdy lekarz przechodzi proces licencjonowania i sprawdzania przeszłości oraz weryfikacji. Gdy wysyłasz wiadomość lub czatujesz z lekarzem na platformie Letmed, możesz zobaczyć jego CV i licencję medyczną.',
        'question-title3': 'Kim są pracownicy służby zdrowia w Letmed?',
        'question-answer3': 'Cały zespół opieki zdrowotnej na platformie Letmed to licencjonowani pracownicy służby zdrowia. Każdy lekarz przechodzi proces licencjonowania i sprawdzania przeszłości oraz weryfikacji. Gdy wysyłasz wiadomość lub czatujesz z lekarzem na platformie Letmed, możesz zobaczyć jego CV i licencję medyczną.',
        'question-title4': 'Czy mogę korzystać z dowolnej apteki?',
        'question-answer4': 'Cały zespół opieki zdrowotnej na platformie Letmed to licencjonowani pracownicy służby zdrowia. Każdy lekarz przechodzi proces licencjonowania i sprawdzania przeszłości oraz weryfikacji. Gdy wysyłasz wiadomość lub czatujesz z lekarzem na platformie Letmed, możesz zobaczyć jego CV i licencję medyczną.',
        'question-title5': 'Czy moje dane osobowe są bezpieczne?',
        'question-answer5': 'Cały zespół opieki zdrowotnej na platformie Letmed to licencjonowani pracownicy służby zdrowia. Każdy lekarz przechodzi proces licencjonowania i sprawdzania przeszłości oraz weryfikacji. Gdy wysyłasz wiadomość lub czatujesz z lekarzem na platformie Letmed, możesz zobaczyć jego CV i licencję medyczną.',
        'nav-lang': 'Usługi',
        'nav-contact': 'Kontakt',
        'nav-cooperation': 'Współpraca'
    }
}

export { langObj }